name: Build

on:
  pull_request:
    types:
      - opened
      - edited
  push:

jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
      - name: .NET Build
        run: dotnet build -c v${{ matrix.configuration }}
        working-directory: src/BoundedRationality
      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: v${{ matrix.configuration }}
          path: ${{ matrix.configuration }}
    strategy:
      matrix:
        configuration: ["1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6"]
